# Generated by Django 5.0.4 on 2025-01-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('labels', '0004_alter_label_unique_together_alter_label_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, default='default-images/default-profile-image.png', null=True, upload_to='contact-images/<built-in function id>/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='labels',
            field=models.ManyToManyField(related_name='contacts', to='labels.label'),
        ),
    ]
