# Generated by Django 5.1.4 on 2025-01-12 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter a valid email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, help_text='089999999', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Please correct valid phone number', regex='^(\\+359|0)?8[789]\\d{7}$')]),
        ),
    ]
