# Generated by Django 5.0.4 on 2025-01-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_image_contact_labels'),
        ('labels', '0005_alter_label_user_alter_label_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, default='default-images/default-profile-image.png', null=True, upload_to='contact-images/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='labels.label'),
        ),
    ]
